apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: lior610/frontend:stable
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:  
            name: urls
        imagePullPolicy: Always
