version: '3.9'
services:
  server:
    image: lior610/frontend:stable
    container_name: frontend
    hostname: frontend
    depends_on:
      - database-api
      - vault
    ports:
      - "5002:80"
    environment:
      - REACT_APP_DATA_API=http://localhost:5001/
      - REACT_APP_LOGIN_API=http://localhost:8000/

  database-api:
    image: lior610/books_database:stable
    container_name: database-api
    hostname: database-api
    environment:
      - ATLAS_CONNECTION_STRING=${ATLAS_CONNECTION_STRING}
    ports:
      - "5001:5001"
  
  vault:
    image: lior610/login:stable
    container_name: vault
    hostname: vault
    environment:
      - ATLAS_CONNECTION_STRING=${ATLAS_CONNECTION_STRING}
    ports:
      - "8000:8000"
