version: '3.9'
services:
  server:
    image: frontend:latest
    container_name: frontend
    hostname: frontend
    depends_on:
      - database-api
      - vault
    ports:
      - "5002:80"

  database-api:
    image: books_database:latest
    container_name: database-api
    hostname: database-api
    environment:
      - ATLAS_CONNECTION_STRING=${ATLAS_CONNECTION_STRING}
    ports:
      - "5001:5001"
  
  vault:
    image: login:latest
    container_name: vault
    hostname: vault
    environment:
      - ATLAS_CONNECTION_STRING=${ATLAS_CONNECTION_STRING}
    ports:
      - "8000:8000"
