apiVersion: apps/v1
kind: Deployment
metadata:
  name: login
spec:
  selector:
    matchLabels:
      app: login
  template:
    metadata:
      labels:
        app: login
    spec:
      containers:
      - name: login
        image: lior610/login:stable
        ports:
        - containerPort: 8000
        envFrom:
        - secretRef:
            name: mongo-secret
