image:
  repository: lior610/books_database
  tag: stable
  pullPolicy: IfNotPresent
replicaCount: 3

service:
  enabled: true
  type: ClusterIP
  port: 5001

secret:
  enabled: true
  name: db-connection-string

extraLabels: {
  component: database-api
}