apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fronetend
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/lior610/book-shelf
    targetRevision: main
    path: book-shelf-chart/chart/books-database
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
