apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "books-database.fullname" . }}
  labels:
    {{- include "books-database.labels" . | nindent 4 }}
    {{- range $key, $val := .Values.extraLabels }}
    {{ $key }}: "{{ $val }}"
    {{- end }}
spec:
  replicas: {{ default 1 .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "books-database.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "books-database.fullname" . }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: {{ required "Image repository is required!" .Values.image.repository }}:{{ default "stable" .Values.image.tag }}
        ports:
        - containerPort: {{ default 5001 .Values.service.port }}
        {{- if .Values.secret.enabled }}
        envFrom:
        - secretRef:
            name: {{ .Values.secret.name }}
        {{- end }}
