apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMap.name }}
  namespace: {{ .Values.namespace }}
data:
  {{- range .Values.configMap.ENV_VARS }}
    {{ .name }}: {{ .value | quote }}
  {{- end }}
