name: CI Pipeline for Database Access

on:
  push:
    branches: [main]
    paths:
      - 'books_database/**'

jobs:
  docker-build-and-push:
    uses: ./.github/workflows/docker-workflow.yml
    with:
      subdirectory: books_database
    secrets: inherit
  deploy:
    uses: ./.github/workflows/deploy-workflow.yml
    with:
      subdirectory: books-database
    secrets: inherit

