name: CI Pipeline for Database Access

on:
  push:
    branches: [main]
    paths:
        - 'books_database/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          path: "books_database/**"
            
      - name: check files
        run: |
          echo "Files in books_database:"
          ls -la books_database


            # - name: Set up Docker Buildx
            #   uses: docker/setup-buildx-action@v3

            # - name: Login to Docker Hub
            #   uses: docker/login-action@v3
            #   with:
            #       username: ${{ secrets.DOCKER_USERNAME }}
            #       password: ${{ secrets.DOCKER_PASSWORD }}

            # - name: Build and push Docker image
            #   uses: docker/build-push-action@v5
            #   with:
            #       context: .
            #       push: true
            #       tags: lior610/actions-example-db-access:latest