name: CI Pipeline for Database Access

on:
  push:
    branches: [main]
    # paths:
    #     - 'books_database/**'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: books_database

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          sparse-checkout: |
            books_database/
          sparse-checkout-cone-mode: false

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: books_database
          push: true
          tags: |
            lior610/books-database:stable
            lior610/books-database:${{ github.run_number }}