name: docker build and push reusable workflow

on:
  push:
    branches:
      - main
#   workflow_call:
#     inputs:
#       subdirectory:
#         type: string
#         description: 'The subdirectory to run the workflow in'
#         required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Update values.yml
        run: |
          sed '/${{ inputs.subdirectory }}:/,/^[^[:space:]]/ s/^\(\s*tag:\s*\).*/\${{ github.run_number }}/' book-shelf-charts/values.yaml
        #   git config --global user.email "actions@github.com"
        #   git config --global user.name "GitHub Actions"
        #   git add k8s/deployment.yaml
        #   git commit -m "Update image to $IMAGE"
        #   git push
