name: apply changes to helm chart values.yaml

on: 
  workflow_call:
    inputs:
      subdirectory:
        type: string
        description: 'The subdirectory to run the workflow in'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Update values.yml
        run: |
          sed "/^${{ inputs.subdirectory }}:/,/^[^[:space:]]/ s/^\(\s*tag:\s*\).*/    tag: ${{ github.run_number }}/" book-shelf-charts/values.yaml
        #   git config --global user.email "actions@github.com"
        #   git config --global user.name "GitHub Actions"
        #   git add book-shelf-charts/values.yaml
        #   git commit -m "Update image to ${{ inputs.subdirectory }} version ${{ github.run_number }}"
        #   git push
