name: docker build and push reusable workflow

on:
  workflow_call:
    inputs:
      subdirectory:
        type: string
        description: 'The subdirectory to run the workflow in'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.subdirectory }} 

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          sparse-checkout: |
            ${{ inputs.subdirectory }}/
          sparse-checkout-cone-mode: false

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ${{ inputs.subdirectory }}
          push: true
          tags: |
            lior610/${{ inputs.subdirectory }}:stable
            lior610/${{ inputs.subdirectory }}:${{ github.run_number }}