name: CI Pipeline for frontend

on:
  push:
    branches: [main]
    paths:
        - 'frontend/**'

jobs:
  docker-build-and-push:
    uses: ./.github/workflows/docker-workflow.yml
    with:
      subdirectory: frontend
    secrets: inherit
  deploy:
    needs: docker-build-and-push
    uses: ./.github/workflows/deploy-workflow.yml
    with:
      subdirectory: frontend
    secrets: inherit