name: CI Pipeline for Authentication Access

on:
  push:
    branches: [main]
    # paths:
    #   - 'books_database/**'

jobs:
  call-workflow-passing-data:
    uses: ./.github/workflows/python-workflow.yml
    with:
      subdirectory: login
    secrets: inherit

