name: CI Pipeline for Authentication Access

on:
  push:
    branches: [main]
    paths:
      - 'login/**'

jobs:
  docker-build-and-push:
    uses: ./.github/workflows/docker-workflow.yml
    with:
      subdirectory: login
    secrets: inherit
  
  deploy:
    needs: docker-build-and-push
    uses: ./.github/workflows/deploy-workflow.yml
    with:
      subdirectory: login
    secrets: inherit

